project:
  type: website
  output-dir: docs

website:
  title: "Iecoinf"
  twitter-card: true
  site-url: https://ecoinf.quarto.pub/iecoinf/
  description: "I Jornadas de Ecoinformática de la AEET que se celebraran en Alcalá de Henares entre el 24 y 25 de octubre de 2024"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: programa.qmd
        text: Programa de las jornadas
      - href: inscripcion.qmd
        text: Inscripción
      - href: alojamiento.qmd
        text: Alojamiento
      - href: resumenes.qmd
        text: Envío de resúmenes
      - href: comite.qmd
        text: Comité organizador
      - href: fechas.qmd
        text: Fechas clave

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    linkcolor: rebeccapurple
