---
title: "Inscripción"
---

La inscripción incluye la asistencia a las conferencias, documentación, cafés, almuerzos diarios y la visita guiada. **El plazo de registro finaliza el 23 de septiembre de 2024**. La inscripción no se considerará formalizada hasta que la secretaría haya confirmado el pago de la misma. **El plazo de pago finaliza el 30 de septiembre de 2024**.

El pago ha de realizarse mediante ingreso en cuenta o trasferencia bancaria a la CC: ES70 0073 01005804 9730 5102, en la entidad Openbank, como tarde el 30 de septiembre de 2024. Los ingresos en cuenta se pueden hacer en cualquier oficina del Banco Santander. Una vez realizado el abono por favor enviános copia del comprobante de pago a secretaria\@aeet.org. No olvides indicar en el formulario los datos que deben constar en la factura.

**Número máximo de asistentes: 35 personas.** Se irá llenando el cupo de asistentes por orden de pago. Una vez completado este cupo no se admitirán más registros.

**Cancelaciones:** Las cancelaciones de asistencia, no motivadas por causa de fuerza mayor, que se hayan notificado con menos de 30 días de antelación al comienzo de las jornadas, no tendrán derecho a reembolso.

**Datos fiscales:**

ASOCIACIÓN ESPAÑOLA DE ECOLOGÍA TERRESTRE

CIF: G50359017

Dpto. Biología y Geología Universidad Rey Juan Carlos, URJC

c/Tulipán s/n 28933 Móstoles, Madrid

**Tarifas de inscripción:**

|                    | Socios\* | No socios |
|--------------------|----------|-----------|
| **Estudiantes**    | 40 €     | 50 €      |
| **No estudiantes** | 50 €     | 60 €      |

\*AEET/AIL/SEEEE/SIBECOL/SPECO

Formulario de asistencia: [rellena este formulario](https://www.aeet.org/forms/38/?_relatedId=2024/10/24/01&title=I%20Jornadas%20de%20Ecoinformatica%20de%20la%20AEET) para saber si estarías interesado en el alojamiento y participación en las actividades paralelas.
