---
title: "Envío de resúmenes"
---

Las comunicaciones serán en formato oral y tendrán una duración de 15 minutos (10 de exposición más 5 de debate o preguntas). Los resúmenes se pueden remitir tanto en inglés como en español. En caso de recibir un número de propuestas de comunicaciones orales superior al número de presentaciones que tienen cabida en el programa, la organización podrá proponer a los autores el cambio a formato comunicación oral flash (5 min). 

El plazo para el envío de resúmenes para las comunicaciones orales está abierto y finaliza el **13 de septiembre de 2024**. Los resúmenes deben contener el título de la comunicación, el nombre y afiliación de los autores, cinco palabras clave y un resumen de aproximadamente 250 palabras. Deben ser remitidos por email a [ecoinf.aeet\@gmail.com](mailto:ecoinf.aeet@gmail.com).
[Link a plantilla](https://docs.google.com/document/d/187lXvTeAcALWlzTw2m0T3loH3dIH2e4EhzrqmRw4Jho/edit?usp=sharing)

La semana del **23 de septiembre de 2024** se comunicará a los autores la aceptación y el formato de sus comunicaciones.


